window.BICICLETEROS_DATA = {
    "schemaVersion":  3,
    "origen":  "BICICLETERO 2026.xlsx",
    "actualizado":  "2026-09-27T21:06:28",
    "total":  82,
    "registros":  [
                      {
                          "id":  "1",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "2",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "3",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "4",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "5",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "6",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "7",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "8",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "9",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "10",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "11",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "12",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "13",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "14",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "15",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "16",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "17",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "18",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "19",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "20",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "21",
                          "zona":  "ACCESO VEHICULAR",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "bicicleta-default.svg",
                          "imageUrl":  "./images/bicicleta-default.svg",
                          "hasPhoto":  false,
                          "observacion":  ""
                      },
                      {
                          "id":  "22",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "420",
                          "nombre":  "PABLO SILVA",
                          "marca":  "OXFORD 29",
                          "color":  "AZUL",
                          "estado":  true,
                          "imagen":  "22.jpeg",
                          "imageUrl":  "./images/22.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "23",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "23.jpeg",
                          "imageUrl":  "./images/23.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "24",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "715",
                          "nombre":  "MELISSA GONZALEZ",
                          "marca":  "TREEK",
                          "color":  "PLATEADA",
                          "estado":  true,
                          "imagen":  "24.jpeg",
                          "imageUrl":  "./images/24.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "25",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "709",
                          "nombre":  "DIEGO PINTO",
                          "marca":  "TREEK",
                          "color":  "NEGRA",
                          "estado":  true,
                          "imagen":  "25.jpeg",
                          "imageUrl":  "./images/25.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "26",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "203",
                          "nombre":  "NICOLAS CHOMALI",
                          "marca":  "CROSSBIKE",
                          "color":  "VERDE",
                          "estado":  true,
                          "imagen":  "26.jpeg",
                          "imageUrl":  "./images/26.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "27",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "301",
                          "nombre":  "FRANCISCO TAPIA",
                          "marca":  "TREK",
                          "color":  "GRIS GRAFITO CON LETRAS ROJAS",
                          "estado":  true,
                          "imagen":  "27.jpeg",
                          "imageUrl":  "./images/27.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "28",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "704",
                          "nombre":  "VIVIANA PEREZ",
                          "marca":  "TREK",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "28.jpeg",
                          "imageUrl":  "./images/28.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "29",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "215",
                          "nombre":  "TOMAS ROJAS",
                          "marca":  "FELT",
                          "color":  "ROJO",
                          "estado":  false,
                          "imagen":  "29.jpeg",
                          "imageUrl":  "./images/29.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "30",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "406",
                          "nombre":  "NATALIA PERALTA",
                          "marca":  "TREEK",
                          "color":  "GRIS/VERDE",
                          "estado":  true,
                          "imagen":  "30.jpeg",
                          "imageUrl":  "./images/30.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "31",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "603",
                          "nombre":  "CAROL LABBE",
                          "marca":  "TREEK",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "31.jpeg",
                          "imageUrl":  "./images/31.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "32",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "508",
                          "nombre":  "BENJAMIN RUIZ-TAGLE",
                          "marca":  "TREEK",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "32.jpeg",
                          "imageUrl":  "./images/32.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "33",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "716",
                          "nombre":  "MARÍA JOSÉ PALACIOS",
                          "marca":  "UPLAND",
                          "color":  "CELESTE",
                          "estado":  true,
                          "imagen":  "33.jpeg",
                          "imageUrl":  "./images/33.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "34",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "519",
                          "nombre":  "ROXANY LOMBANA",
                          "marca":  "BIANCHI",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "34.jpeg",
                          "imageUrl":  "./images/34.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "35",
                          "zona":  "ACCESO PEATONAL",
                          "dpto":  "501",
                          "nombre":  "MARIA VEITIA",
                          "marca":  "RALEIGH",
                          "color":  "VERDE/FOSFORESCENTE",
                          "estado":  true,
                          "imagen":  "35.jpeg",
                          "imageUrl":  "./images/35.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "35.B",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "35-B.jpeg",
                          "imageUrl":  "./images/35-B.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "36",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "103",
                          "nombre":  "LESLIE PEREZ",
                          "marca":  "GT/LAGUNA",
                          "color":  "NEGRO/ MORADO",
                          "estado":  true,
                          "imagen":  "36.jpeg",
                          "imageUrl":  "./images/36.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "37",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "616",
                          "nombre":  "NATALIA FARIAS",
                          "marca":  "OXFORD",
                          "color":  "AMARILLO CON BLANCO",
                          "estado":  true,
                          "imagen":  "37.jpeg",
                          "imageUrl":  "./images/37.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "38",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "305",
                          "nombre":  "RAYEN SAN MARTIN",
                          "marca":  "OXFORD",
                          "color":  "TURQUESA",
                          "estado":  true,
                          "imagen":  "38.jpeg",
                          "imageUrl":  "./images/38.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "39",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "716",
                          "nombre":  "MARÍA JOSÉ PALACIOS",
                          "marca":  "UNLAND",
                          "color":  "CALIPSO",
                          "estado":  true,
                          "imagen":  "39.jpeg",
                          "imageUrl":  "./images/39.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "40",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "707",
                          "nombre":  "MICHAEL FIGUEROA",
                          "marca":  "TREEK MARLIN 7",
                          "color":  "AZUL MARINO",
                          "estado":  true,
                          "imagen":  "40.jpeg",
                          "imageUrl":  "./images/40.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "41",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "104",
                          "nombre":  "MARCELO FOUCAUT",
                          "marca":  "JEEP",
                          "color":  "BLANCA",
                          "estado":  true,
                          "imagen":  "41.jpeg",
                          "imageUrl":  "./images/41.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "42",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "515",
                          "nombre":  "IVAN SARPI",
                          "marca":  "KONA",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "42.jpeg",
                          "imageUrl":  "./images/42.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "43",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "306",
                          "nombre":  "CRISTIÁN ARAVENA",
                          "marca":  "TREK",
                          "color":  "NARANJA GRIS",
                          "estado":  true,
                          "imagen":  "43.jpeg",
                          "imageUrl":  "./images/43.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "44",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "318",
                          "nombre":  "ADRIAN MORALES",
                          "marca":  "JEEP",
                          "color":  "NEGRO VERDE",
                          "estado":  true,
                          "imagen":  "44.jpeg",
                          "imageUrl":  "./images/44.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "45",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "610",
                          "nombre":  "LAURA BARTOLOTTI",
                          "marca":  "OXFORD",
                          "color":  "NEGRO CON CANASTO",
                          "estado":  false,
                          "imagen":  "45.jpeg",
                          "imageUrl":  "./images/45.jpeg",
                          "hasPhoto":  true,
                          "observacion":  "ESPACIO DE BICICLETERO OCUPADO POR OTRO RESIDENTE."
                      },
                      {
                          "id":  "46",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "513",
                          "nombre":  "ANDREA SCOFFIER",
                          "marca":  "TRINX/KRAKKEN AFRODITA",
                          "color":  "GRIS/GRAFITO/METALICO",
                          "estado":  true,
                          "imagen":  "46.jpeg",
                          "imageUrl":  "./images/46.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "47",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "510",
                          "nombre":  "CARLOS BELMAR",
                          "marca":  "TREK",
                          "color":  "NEGRA",
                          "estado":  false,
                          "imagen":  "47.jpeg",
                          "imageUrl":  "./images/47.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "48",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "502",
                          "nombre":  "GIANCARLO MUSSATO",
                          "marca":  "TREEK MARLIN 5",
                          "color":  "PLOMA",
                          "estado":  true,
                          "imagen":  "48.jpeg",
                          "imageUrl":  "./images/48.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "49",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "514",
                          "nombre":  "BRAULIO ALIAGA",
                          "marca":  "BIANCHI/CON SILLA DE NIÑO",
                          "color":  "CALIPSO",
                          "estado":  true,
                          "imagen":  "49.jpeg",
                          "imageUrl":  "./images/49.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "50",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "312",
                          "nombre":  "KARLA PÉREZ",
                          "marca":  "S/MARCA",
                          "color":  "NEGRA",
                          "estado":  true,
                          "imagen":  "50.jpeg",
                          "imageUrl":  "./images/50.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "51",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "608",
                          "nombre":  "LEANDRO CAMPILLAY",
                          "marca":  "P3/CYCLE",
                          "color":  "NEGRA/NARANJO",
                          "estado":  false,
                          "imagen":  "51.jpeg",
                          "imageUrl":  "./images/51.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "52",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "408",
                          "nombre":  "DAVID AHUMADA",
                          "marca":  "TREK CROSS",
                          "color":  "NEGRA",
                          "estado":  true,
                          "imagen":  "52.jpeg",
                          "imageUrl":  "./images/52.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "53",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "KONA",
                          "color":  "MARRON",
                          "estado":  false,
                          "imagen":  "53.jpeg",
                          "imageUrl":  "./images/53.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "54",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "505",
                          "nombre":  "LILIA FUENTEALBA",
                          "marca":  "VIRTUE",
                          "color":  "NEGRO",
                          "estado":  false,
                          "imagen":  "54.jpeg",
                          "imageUrl":  "./images/54.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "55",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "708",
                          "nombre":  "THALIA SANCHEZ",
                          "marca":  "BIANCHI",
                          "color":  "GRIS/NEGRO/ROJO",
                          "estado":  true,
                          "imagen":  "55.jpeg",
                          "imageUrl":  "./images/55.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "56",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "320",
                          "nombre":  "ALBA ACUÑA",
                          "marca":  "TREK",
                          "color":  "GRIS/LETRAS ROJAS",
                          "estado":  true,
                          "imagen":  "56.jpeg",
                          "imageUrl":  "./images/56.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "57",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "704",
                          "nombre":  "VIVIANA PEREZ",
                          "marca":  "TREK X-CALIBER 8",
                          "color":  "GRIS LETRA NEGRA",
                          "estado":  true,
                          "imagen":  "57.jpeg",
                          "imageUrl":  "./images/57.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "58",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "BIANCHI",
                          "color":  "CELESTE",
                          "estado":  false,
                          "imagen":  "58.jpeg",
                          "imageUrl":  "./images/58.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "59",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "204",
                          "nombre":  "FELIPE ARRIAGADA",
                          "marca":  "OXIGEN",
                          "color":  "NEGRO",
                          "estado":  true,
                          "imagen":  "59.jpeg",
                          "imageUrl":  "./images/59.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "60",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "207",
                          "nombre":  "EDUARDO ESCOBAR",
                          "marca":  "GT",
                          "color":  "VERDE-NEGRO",
                          "estado":  true,
                          "imagen":  "60.jpeg",
                          "imageUrl":  "./images/60.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "61",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "418",
                          "nombre":  "HERNAN GOMEZ",
                          "marca":  "TREEK 3700",
                          "color":  "AZUL",
                          "estado":  true,
                          "imagen":  "61.jpeg",
                          "imageUrl":  "./images/61.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "62",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "506",
                          "nombre":  "FELIPE RODRIGUEZ",
                          "marca":  "GIANT",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "62.jpeg",
                          "imageUrl":  "./images/62.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "63",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "63.jpeg",
                          "imageUrl":  "./images/63.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "64",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "505",
                          "nombre":  "LILIA FUENTEALBA",
                          "marca":  "TREK SKYE",
                          "color":  "NEGRO",
                          "estado":  false,
                          "imagen":  "64.jpeg",
                          "imageUrl":  "./images/64.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "65",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "713",
                          "nombre":  "LISSETTE OVALLES",
                          "marca":  "VIRTUE",
                          "color":  "NEGRO",
                          "estado":  false,
                          "imagen":  "65.jpeg",
                          "imageUrl":  "./images/65.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "66",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "216",
                          "nombre":  "JAIME SALDIAS",
                          "marca":  "OXFORD",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "66.jpeg",
                          "imageUrl":  "./images/66.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "67",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "517",
                          "nombre":  "FRANCHESCA CONTRERAS",
                          "marca":  "FIERCE",
                          "color":  "NEGRO/AZUL",
                          "estado":  true,
                          "imagen":  "67.jpeg",
                          "imageUrl":  "./images/67.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "68",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "68.jpeg",
                          "imageUrl":  "./images/68.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "69",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "69.jpeg",
                          "imageUrl":  "./images/69.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "70",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "OXFORD",
                          "color":  "AZUL LETRA NEGRA",
                          "estado":  false,
                          "imagen":  "70.jpeg",
                          "imageUrl":  "./images/70.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "71",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "309",
                          "nombre":  "MARCCELO MUÑOZ",
                          "marca":  "TREEK",
                          "color":  "NEGRO DETALE ROJO/AZUL",
                          "estado":  true,
                          "imagen":  "71.jpeg",
                          "imageUrl":  "./images/71.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "72",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "72.jpeg",
                          "imageUrl":  "./images/72.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "73",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "73.jpeg",
                          "imageUrl":  "./images/73.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "74",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "74.jpeg",
                          "imageUrl":  "./images/74.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "75",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "",
                          "color":  "",
                          "estado":  false,
                          "imagen":  "75.jpeg",
                          "imageUrl":  "./images/75.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "76",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "NORCO",
                          "color":  "NEGRO",
                          "estado":  false,
                          "imagen":  "76.jpeg",
                          "imageUrl":  "./images/76.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "77",
                          "zona":  "PASILLO TORRE A (-1)",
                          "dpto":  "620",
                          "nombre":  "YENNY LOPEZ",
                          "marca":  "AVALANCE BIANCI",
                          "color":  "GRIS",
                          "estado":  true,
                          "imagen":  "77.jpeg",
                          "imageUrl":  "./images/77.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "78",
                          "zona":  "PASILLO TORRE A (-2)",
                          "dpto":  "506",
                          "nombre":  "FELIPE RODRIGUEZ",
                          "marca":  "LIV",
                          "color":  "NEGRA",
                          "estado":  true,
                          "imagen":  "78.jpeg",
                          "imageUrl":  "./images/78.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "79",
                          "zona":  "PASILLO TORRE A (-2)",
                          "dpto":  "414",
                          "nombre":  "DANIELA PRADO",
                          "marca":  "TREK",
                          "color":  "NEGRA",
                          "estado":  true,
                          "imagen":  "79.jpeg",
                          "imageUrl":  "./images/79.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "80",
                          "zona":  "PASILLO TORRE A (-2)",
                          "dpto":  "413",
                          "nombre":  "DAVE RODRIGUEZ",
                          "marca":  "BODY GLOVE",
                          "color":  "ROJA",
                          "estado":  true,
                          "imagen":  "80.jpeg",
                          "imageUrl":  "./images/80.jpeg",
                          "hasPhoto":  true,
                          "observacion":  ""
                      },
                      {
                          "id":  "81",
                          "zona":  "PASILLO TORRE A (-2)",
                          "dpto":  "",
                          "nombre":  "",
                          "marca":  "WOLF",
                          "color":  "GRIS PLATA",
                          "estado":  false,
                          "imagen":  "81.jpeg",
                          "imageUrl":  "./images/81.jpeg",
                          "hasPhoto":  true,
                          "observacion":  "se mudo"
                      }
                  ]
};
